### PR TITLE
Added function write_solid to generate blocked STL files

### PR DESCRIPTION
**Pull request by oyvindbreivik**
Hi,

Thanks for providing this nice library! I've used it for milling 3D models of topographic maps. I've added a function called write_solid for creating "blocked" surfaces. This is useful for 3D-printing since most  3D printers require a solid rather than an infinitely thin surface. I've also added a new option to your write function where the normals and their respective vertices are handled in reverse order to allow the normals to point in the opposite direction (option inverse=False is the default). This is useful for surfaces created using np.mgrid[] which produces matrices with the connecitivity in reverse order compared to np.meshgrid().

### CODE REVIEW

**Comment by asahidari** [comment]
Thank you for your suggestion and PR! I will check it and come back soon.

**Comment by asahidari** [comment]
Thank you for your contribution 😄, I read your code.

Your idea, exporting solid model, is actually interesting. However, I am afraid it has some limitations: the thickness is always in direction of z axis (some surface may need another direction); the desirable direction of thickness is the normal direction of each faces; it may not work properly for some surfaces, such as sphere and torus. The function you implemented is, in fact, simple and easy to use, but I'm afraid some users might complain about the limitation and the accuracy.

Another feature you mentioned, reversing face normals, is also captivating. But when you can change surface direction by using np.mgrid instead of np.meshgrid (or vice versa), it seems no need to add "inverse" option.

For these reasons mentioned above, I would like to decline the PR this time. I'm sorry, but this is the first PR I received (I'm flattered), I really appreciate your suggestion.

**Comment by oyvindbreivik** [comment]
Ok, no problem. I took the idea from the surf2solid
<https://www.mathworks.com/matlabcentral/fileexchange/42876-surf2solid-make-a-solid-volume-from-a-surface-for-3d-printing>
Matlab code. Solids are needed if you want to 3d print a file since
printers need volumes rather than surfaces.
The “blocked” version that I've coded up is as you mentioned only meant for
surfaces, but this is not a big problem as surfaces are usually defined in
the z direction.

The Matlab code also describes how to "thicken" a surface rather than
blocking it. This could be added, and indeed I've considered doing so, but
I haven't got around to it yet.

Best

Oyvind

**Comment by asahidari** [comment]
I did not know 'surf2solid' already exists in MATLAB, thank you for the link. The script is intriguing, and now I understand why you want to add the feature. And I understand that the 'block' version you implemented is equivalent to the 'ELEVATION' option in MATLAB script.

Anyway, it seems good to separate 'surf2solid' script from 'surf2stl' just like MATLAB scripts, because the purposes of them are different from each other, and the code would be too long when fully implemented. So I will close this PR later.

Implementing the script seems worth trying, I hope it will go well.

Best regards.

asahidari

**Pull request closed without merging**
